///////////////////////////////////////////////////////////
//  Administrador.cs
//  Implementation of the Class Administrador
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Administrador : Usuario {

	public Administrador(int idx, string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass)
		: base(idx, apellidoM, apellidoP, direc, dni, email, nombre, telF, telM, usuario, pass )
    {

	}

    public Administrador( string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass)
        : base( apellidoM, apellidoP, direc, dni, email, nombre, telF, telM, usuario, pass)
    {

    }
}//end Administrador