///////////////////////////////////////////////////////////
//  Administrador.cs
//  Implementation of the Class Administrador
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Administrador : Usuario {

	public ControlAdministrador m_ControlAdministrador;

	public Administrador(){

	}

	~Administrador(){

	}

	public void AgregarDentista(){

	}

	public void AgregarSecretaria(){

	}

	public void ConsultarDentistas(){

	}

	public void ConsultarEstadisticasDeNegocio(){

	}

	public void ConsultarHistorialDeCitas(){

	}

	public void ConsultarPacientes(){

	}

	public void ConsultarReportes(){

	}

	public void ConsultarSecretarias(){

	}

	public void EliminarDentista(){

	}

	public void EliminarSecretaria(){

	}

	public void ModificarDentista(){

	}

	public void ModificarSecretaria(){

	}

}//end Administrador