///////////////////////////////////////////////////////////
//  Agenda.cs
//  Implementation of the Class Agenda
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Agenda {

	private string IDMedico;
	public ControlAgenda m_ControlAgenda;

	public Agenda(){

	}

	~Agenda(){

	}

}//end Agenda