///////////////////////////////////////////////////////////
//  CajaRegistradora.cs
//  Implementation of the Class CajaRegistradora
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Clases;



public class CajaRegistradora {

    public int IdCaja { set; get; }
    public string Nombre { get; set; }
    public string Ubicacion { get; set; }
    public DateTime FechaHoraApertura { set; get; }
    public DateTime FechaHoraCierre { get; set; }
    public string Estado { get; set; }
    public int IdUsuario { get; set; }
    public decimal SaldoInicial { get; set; }
    public decimal SaldoFinal { get; set; }
    public List<Venta> Ventas { set; get; }
    public float Total { set; get; }

    ControlVentas controlVentas = new ControlVentas();

    public CajaRegistradora( string nombre, string ubicacion, int idx_usuario, decimal saldoI )
    {
        Nombre = nombre;
        Ubicacion = ubicacion;
        IdUsuario = idx_usuario;
        SaldoInicial = saldoI;
    }

    private float CalcularTotal()
    {
        float total = 0;
        foreach (Venta venta in Ventas)
        {
            total += (float)venta.subtotal;
        }
        return total;
    }

    public CajaRegistradora( int idx, string nombre, string ubicacion, DateTime fhApert, DateTime fhCierr, string edo, int idx_usuario, decimal saldoI, decimal saldoF )
    {
        IdCaja = idx;
        Nombre = nombre;
        Ubicacion = ubicacion;
        FechaHoraApertura = fhApert;
        FechaHoraCierre = fhCierr;
        Estado = edo;
        IdUsuario = idx_usuario;
        SaldoInicial = saldoI;
        SaldoFinal = saldoF;
        Ventas = controlVentas.consultarVentas(IdCaja);
        Total = CalcularTotal();
    }
}//end CajaRegistradora