///////////////////////////////////////////////////////////
//  CajaRegistradora.cs
//  Implementation of the Class CajaRegistradora
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CajaRegistradora {

	private double DineroAlDia;
	private string Fecha;
	private string idCaja;
	private List<Medicamento> ProductosVendidosAlDia;
	private double Total;
	public ControlCajaRegistradora m_ControlCajaRegistradora;

	public CajaRegistradora(){

	}

	~CajaRegistradora(){

	}

}//end CajaRegistradora