///////////////////////////////////////////////////////////
//  Cita.cs
//  Implementation of the Class Cita
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Cita {

    public string IDCita { set; get; }
    public byte Duracion { set; get; }
    public string Estado { set; get; }
    public string Fecha { set; get; }
    public string FechaDeGeneracion { set; get; }
    public string Hora { set; get; }
    public string IDMedico { set; get; }
    public string IDPaciente { set; get; }
    public string MotivoDeCita { set; get; }
    public string Nota { set; get; }

    public ControlCita m_ControlCita;

	public Cita(){

	}

	~Cita(){

	}

}//end Cita