///////////////////////////////////////////////////////////
//  Cita.cs
//  Implementation of the Class Cita
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Cita {

	private byte Duracion;
	private string Estado;
	private string Fecha;
	private string FechaDeGeneracion;
	private string Hora;
	private string IDCita;
	private string IDMedico;
	private string IDPaciente;
	private string MotivoDeCita;
	private string Nota;
	public ControlCita m_ControlCita;

	public Cita(){

	}

	~Cita(){

	}

}//end Cita