///////////////////////////////////////////////////////////
//  Cita.cs
//  Implementation of the Class Cita
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Cita {

    public int IDCita { set; get; }
    public byte Duracion { set; get; }
    public string Estado { set; get; }
    public DateOnly Fecha { set; get; }
    public DateOnly FechaDeGeneracion { set; get; }
    public TimeOnly Hora { set; get; }
    public int IDMedico { set; get; }
    public int IDPaciente { set; get; }
    public string MotivoDeCita { set; get; }
    public string Nota { set; get; }

    public ControlCita m_ControlCita;

	public Cita( int idcita, byte dur, string edo, DateOnly date, DateOnly dategeneracion, TimeOnly hour, int idmedico, int idpaciente, string motivo, string nota ){
        IDCita = idcita;
        Duracion = dur;
        Estado = edo;
        Fecha = date;
        FechaDeGeneracion = dategeneracion;
        Hora = hour;
        IDMedico = idmedico;
        IDPaciente = idpaciente;
        MotivoDeCita = motivo;
        Nota = nota;
    }

    public Cita( byte dur, string edo, DateOnly date, DateOnly dategeneracion, TimeOnly hour, int idmedico, int idpaciente, string motivo, string nota)
    {
        Duracion = dur;
        Estado = edo;
        Fecha = date;
        FechaDeGeneracion = dategeneracion;
        Hora = hour;
        IDMedico = idmedico;
        IDPaciente = idpaciente;
        MotivoDeCita = motivo;
        Nota = nota;
    }

}//end Cita