///////////////////////////////////////////////////////////
//  ConsultaMedica.cs
//  Implementation of the Class ConsultaMedica
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ConsultaMedica {

    public int IDConsulta { set; get; }
    public string Diagnostico { set; get; }
    public DateOnly Fecha { set; get; }
    public int IDDentista { set; get; }
    public int IDPaciente { set; get; }
    public int IDProximaCita { set; get; }
    public int IDReceta { set; get; }
    public string MotivoDeConsulta { set; get; }

    public ConsultaMedica( int idConsulta, string diagnostico, DateOnly fecha, int idDentista, int idPaciente, int idReceta, string motivoDeConsulta)
    {
        IDConsulta = idConsulta;
        Diagnostico = diagnostico;
        Fecha = fecha;
        IDDentista = idDentista;
        IDPaciente = idPaciente;
        IDReceta = idReceta;
        MotivoDeConsulta = motivoDeConsulta;
    }

    public ConsultaMedica(string diagnostico, DateOnly fecha, int idDentista, int idPaciente, int idReceta, string motivoDeConsulta)
    {
        Diagnostico = diagnostico;
        Fecha = fecha;
        IDDentista = idDentista;
        IDPaciente = idPaciente;
        IDReceta = idReceta;
        MotivoDeConsulta = motivoDeConsulta;
    }

}//end ConsultaMedica