///////////////////////////////////////////////////////////
//  ConsultaMedica.cs
//  Implementation of the Class ConsultaMedica
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ConsultaMedica {

	private string Diagnostico;
	private string Fecha;
	private string IDConsulta;
	private string IDDentista;
	private string IDPaciente;
	private string IDProximaCita;
	private string IDReceta;
	private string MotivoDeConsulta;
	public ControlConsulta m_ControlConsulta;

	public ConsultaMedica(){

	}

	~ConsultaMedica(){

	}

}//end ConsultaMedica