///////////////////////////////////////////////////////////
//  ControlPaciente.cs
//  Implementation of the Class ControlPaciente
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlPaciente {

	public ControlMedico m_ControlMedico;

	public ControlPaciente(){

	}

	~ControlPaciente(){

	}

	/// 
	/// <param name="paciente"></param>
	public void AgregarPaciente(Paciente paciente){

	}

	/// 
	/// <param name="paciente"></param>
	public void CargarPaciente(Paciente paciente){

	}

	/// 
	/// <param name="IDPaciente"></param>
	public void ConsultarPaciente(string IDPaciente){

	}

	/// 
	/// <param name="idDentista"></param>
	public List<Paciente> ConsultarPacientes(string idDentista){

		return null;
	}

	/// 
	/// <param name="IDPaciente"></param>
	public bool EliminarPaciente(string IDPaciente){

		return false;
	}

	/// 
	/// <param name="paciente"></param>
	public bool GuardarPaciente(Paciente paciente){

		return false;
	}

	/// 
	/// <param name="IDPaciente"></param>
	public void ModificarPaciente(string IDPaciente){

	}

}//end ControlPaciente