///////////////////////////////////////////////////////////
//  ControlMedico.cs
//  Implementation of the Class ControlMedico
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlMedico {

	public ControlMedico(){

	}

	~ControlMedico(){

	}

	/// 
	/// <param name="medico"></param>
	public void AgregarMedico(Medico medico){

	}

	/// 
	/// <param name="medico"></param>
	public void CarcargMedico(Medico medico){

	}

	/// 
	/// <param name="IDMedico"></param>
	public void ConsultarMedico(string IDMedico){

	}

	public void ConsultarMedicos(){

	}

	/// 
	/// <param name="IDMedico"></param>
	public bool EliminarMedico(string IDMedico){

		return false;
	}

	/// 
	/// <param name="IDMedico"></param>
	public void ModificarMedico(string IDMedico){

	}

}//end ControlMedico