///////////////////////////////////////////////////////////
//  ControlAgenda.cs
//  Implementation of the Class ControlAgenda
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlAgenda {

	public ControlMedico m_ControlMedico;
	public frmDentista m_frmDentista;

	public ControlAgenda(){

	}

	~ControlAgenda(){

	}

	public void AgendarCita(){

	}

	public void CargarAgenda(){

	}

	/// 
	/// <param name="IDMedico"></param>
	public void ConsultarCitas(string IDMedico){

	}

	/// 
	/// <param name="IDCita"></param>
	public void EliminarCita(string IDCita){

	}

	/// 
	/// <param name="IDCIta"></param>
	public void ModificarCita(string IDCIta){

	}

}//end ControlAgenda