///////////////////////////////////////////////////////////
//  ControlCita.cs
//  Implementation of the Class ControlCita
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlCita {

	public Reporte m_Reporte;

	public ControlCita(){

	}

	~ControlCita(){

	}

	/// 
	/// <param name="cita"></param>
	public void CargarCita(Cita cita){

	}

	/// 
	/// <param name="IDCita"></param>
	public Cita ConsultarCita(string IDCita){

		return null;
	}

	/// 
	/// <param name="idDentista"></param>
	public List<Cita> ConsultarCitas(string idDentista){

		return null;
	}

	public void CrearCita(){

	}

	/// 
	/// <param name="IDCita"></param>
	public void EliminarCita(string IDCita){

	}

	/// 
	/// <param name="Cita"></param>
	public bool GuardarCita( Cita cita ){

		return false;
	}

	/// 
	/// <param name="cita"></param>
	public void ModificarCita(Cita cita){

	}

}//end ControlCita