///////////////////////////////////////////////////////////
//  ControlReceta.cs
//  Implementation of the Class ControlReceta
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlReceta {

	public ControlMedico m_ControlMedico;
	public frmDentista m_frmDentista;
	public frmAdministrador m_frmAdministrador;

	public ControlReceta(){

	}

	~ControlReceta(){

	}

	public void AgregarReceta(){

	}

	/// 
	/// <param name="IDReceta"></param>
	public void ConsultarReceta(string IDReceta){

	}

	/// 
	/// <param name="idDentista"></param>
	public List<Receta> ConsultarRecetas(string idDentista){

		return null;
	}

	/// 
	/// <param name="IDReceta"></param>
	public bool EliminarReceta(string IDReceta){

		return false;
	}

	/// 
	/// <param name="IDReceta"></param>
	public void ModificarReceta(string IDReceta){

	}

}//end ControlReceta