///////////////////////////////////////////////////////////
//  ControlReporte.cs
//  Implementation of the Class ControlReporte
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlReporte {

	public ControlMedico m_ControlMedico;

	public ControlReporte(){

	}

	~ControlReporte(){

	}

	public void AgregarReporte(){

	}

	public void ConsultarReportes(){

	}

	/// 
	/// <param name="IDReporte"></param>
	public void EliminarReporte(string IDReporte){

	}

}//end ControlReporte