///////////////////////////////////////////////////////////
//  ControlAdministrador.cs
//  Implementation of the Class ControlAdministrador
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:48 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlAdministrador {

	public ControlAdministrador(){

	}

	~ControlAdministrador(){

	}

	public void AgregarAdministrador(){

	}

	/// 
	/// <param name="id"></param>
	public Administrador ConsultarAdministrador( int id){

		return null;
	}

	public List<Administrador> ConsultarAdministradorers(){

		return null;
	}

	/// 
	/// <param name="id"></param>
	public bool EliminarAdministrador(String id){

		return false;
	}

	/// 
	/// <param name="id"></param>
	public bool ModificarAdministrador(String id){

		return false;
	}

}//end ControlAdministrador