///////////////////////////////////////////////////////////
//  ControlRespuestasClinicas.cs
//  Implementation of the Class ControlRespuestasClinicas
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlRespuestasClinicas {

	public ControlReporte m_ControlReporte;

	public ControlRespuestasClinicas(){

	}

	~ControlRespuestasClinicas(){

	}

	public void AgregarRespuestas(){

	}

	/// 
	/// <param name="IDPaciente"></param>
	public void ConsultarRespuestas(string IDPaciente){

	}

	/// 
	/// <param name="IDRespuestas"></param>
	public void EliminarRespuestas(string IDRespuestas){

	}

	/// 
	/// <param name="IDRespuestas"></param>
	public void ModificarRespuestas(string IDRespuestas){

	}

}//end ControlRespuestasClinicas