///////////////////////////////////////////////////////////
//  ControlPreguntas.cs
//  Implementation of the Class ControlPreguntas
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlPreguntas {

	public ControlMedico m_ControlMedico;
	public frmDentista m_frmDentista;

	public ControlPreguntas(){

	}

	~ControlPreguntas(){

	}

	public void AgregarPregunta(){

	}

	public List<PreguntaHistoriaClinica> ConsultarPreguntas(){

		return null;
	}

	/// 
	/// <param name="IDPregunta"></param>
	public bool EliminarPregunta(string IDPregunta){

		return false;
	}

	/// 
	/// <param name="IDPregunta"></param>
	public bool ModificarPregunta(string IDPregunta){

		return false;
	}

}//end ControlPreguntas