///////////////////////////////////////////////////////////
//  ControlConsulta.cs
//  Implementation of the Class ControlConsulta
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
//using Clases;


public class ControlConsulta {

	public ControlMedico m_ControlMedico;
	/*
	public frmDentista m_frmDentista;
	public frmAdministrador m_frmAdministrador;*/

	public ControlConsulta(){

	}

	~ControlConsulta(){

	}

	public void AgregarConsulta(){

	}

	/// 
	/// <param name="string"></param>
	public List<ConsultaMedica> ConsultarConsultasMedicas( string idDentista ){

		return null;
	}

	/// 
	/// <param name="IDConsulta"></param>
	public void EliminarConsultar(string IDConsulta){

	}

	/// 
	/// <param name="IDConsulta"></param>
	public void ModificarConsulta(string IDConsulta){

	}

}//end ControlConsulta