///////////////////////////////////////////////////////////
//  ControlPresupuesto.cs
//  Implementation of the Class ControlPresupuesto
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlPresupuesto {

	public ControlReporte m_ControlReporte;
	public frmDentista m_frmDentista;
	public frmAdministrador m_frmAdministrador;

	public ControlPresupuesto(){

	}

	~ControlPresupuesto(){

	}

	public void AgregarPresupuesto(){

	}

	/// 
	/// <param name="IDPresupuesto"></param>
	public void ConsultarPresupuesto(string IDPresupuesto){

	}

	public void ConsultarPresupuestos(){

	}

	public void EliminarPresupuesto(){

	}

	public void ModificarPresupuesto(){

	}

}//end ControlPresupuesto