///////////////////////////////////////////////////////////
//  ControlMedicamento.cs
//  Implementation of the Class ControlMedicamento
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlMedicamento {

	public Reporte m_Reporte;
	public frmSecretaria m_frmSecretaria;
	public frmAlmacen m_frmAlmacen;
	public frmAdministrador m_frmAdministrador;

	public ControlMedicamento(){

	}

	~ControlMedicamento(){

	}

	public void AgregarMedicamento(){

	}

	/// 
	/// <param name="IDMedicamento"></param>
	public void ConsultarMedicamento(string IDMedicamento){

	}

	public void ConsultarMedicamentos(){

	}

	/// 
	/// <param name="IDMedicamento"></param>
	public void EliminarMediacamento(string IDMedicamento){

	}

	public void ModificarMedicamento(){

	}

	public void VenderMedicamento(){

	}

}//end ControlMedicamento