///////////////////////////////////////////////////////////
//  ControlCajaRegistradora.cs
//  Implementation of the Class ControlCajaRegistradora
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlCajaRegistradora {

	public ControlSecretaria m_ControlSecretaria;
	public ControlReporte m_ControlReporte;
	public frmSecretaria m_frmSecretaria;

	public ControlCajaRegistradora(){

	}

	~ControlCajaRegistradora(){

	}

	/// 
	/// <param name="medicamento"></param>
	public void AgregarMedicamentoAVenta(Medicamento medicamento){

	}

	public void ConsultarMedicamentos(){

	}

	public void ConsultarMedicamentosVendidosHOY(){

	}

	/// 
	/// <param name="idVenta"></param>
	public Venta ConsultarVenta(string idVenta){

		return null;
	}

	public void ConsultarVentas(){

	}

	/// 
	/// <param name="IDMedicamento"></param>
	public void EliminarMedicamento(string IDMedicamento){

	}

}//end ControlCajaRegistradora