///////////////////////////////////////////////////////////
//  ControlSecretaria.cs
//  Implementation of the Class ControlSecretaria
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ControlSecretaria {

	public ControlSecretaria(){

	}

	~ControlSecretaria(){

	}

	/// 
	/// <param name="secretaria"></param>
	public void AgregarSecretaria(Secretaria secretaria){

	}

	/// 
	/// <param name="IDSecretaria"></param>
	public void ConsultarSecretaria(string IDSecretaria){

	}

	public void ConsultarSecretarias(){

	}

	/// 
	/// <param name="IDSecretaria"></param>
	public void EliminarSecretaria(string IDSecretaria){

	}

	/// 
	/// <param name="IDSecretaria"></param>
	public void ModificarSecretaria(string IDSecretaria){

	}

}//end ControlSecretaria