///////////////////////////////////////////////////////////
//  Medicamento.cs
//  Implementation of the Class Medicamento
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Medicamento {

	private byte Cantidad;
	private string DivicionPisoEstante;
	private string Estante;
	private string IDMedicamento;
	private string Nombre;
	private int PisoEstante;
	private double Precio;
	private string Seccion;
	private double Subtotal;
	private string UnidadDeMedida;
	public ControlMedicamento m_ControlMedicamento;

	public Medicamento(){

	}

	~Medicamento(){

	}

}//end Medicamento