///////////////////////////////////////////////////////////
//  Medico.cs
//  Implementation of the Class Medico
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Medico : Usuario {

	public string IDConsultorio { set; get; }
    public string Turno { set; get; }
    public ControlMedico m_ControlMedico;

	public Medico(int idx, string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass, string turno, string idConsult)
        : base(idx, apellidoM, apellidoP, direc, dni, email, nombre, telF, telM, usuario, pass) {

        IDConsultorio = idConsult;
        Turno = turno;
    }

    public Medico( string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass, string turno, string idConsult)
        : base(apellidoM, apellidoP, direc, dni, email, nombre, telF, telM, usuario, pass)
    {

        IDConsultorio = idConsult;
        Turno = turno;
    }

}//end Medico