///////////////////////////////////////////////////////////
//  Medico.cs
//  Implementation of the Class Medico
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Medico : Usuario {

	public string IDConsultorio { set; get; }
    public string Turno { set; get; }
    public ControlMedico m_ControlMedico;

	public Medico(){

	}

	~Medico(){

	}

	/// 
	/// <param name="IDpaciente"></param>
	public void AgregarPaciente(Paciente IDpaciente){

	}

	public void AgregarReporte(){

	}

	public void ConsularAgenda(){

	}

	/// 
	/// <param name="IDPaciente"></param>
	public void ConsultarPaciente(Paciente IDPaciente){

	}

	public void ConsultarPacientes(){

	}

	public void ConsultarPresupuesto(){

	}

	public void ConsultarTrabajosPorPaciente(){

	}

}//end Medico