///////////////////////////////////////////////////////////
//  Medicamento.cs
//  Implementation of the Class Medicamento
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Medicamento {

    public string IDMedicamento { set; get; }
    public byte Cantidad { set; get; }
    public string DivicionPisoEstante { set; get; }
    public string Estante { set; get; }
    public string Nombre { set; get; }
    public int PisoEstante { set; get; }
    public double Precio { set; get; }
    public string Seccion { set; get; }
    public double Subtotal { set; get; }
    public string UnidadDeMedida { set; get; }
    public ControlMedicamento m_ControlMedicamento;

	public Medicamento(){

	}

	~Medicamento(){

	}

}//end Medicamento