///////////////////////////////////////////////////////////
//  Paciente.cs
//  Implementation of the Class Paciente
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Paciente : Persona {

    public DateOnly FechaNacimiento { set; get; }
    public int IDPreguntasHistoria { set; get; }
    public string Notas { set; get; }
    public float Peso { set; get; }
    public float Talla { set; get; }
    public int Edad { get; set; }
    public float IMC { get; set; }

    public ControlPaciente m_ControlPaciente;

	public Paciente(int idx, string apellidoM, string apellidoP, string direc, string email, string nombre, string telF, string telM, DateOnly nacimiento, int idRespestas, string notas, float peso, float talla)
        : base(idx, apellidoM, apellidoP, direc, email, nombre, telF, telM ) 
    { 

        FechaNacimiento = nacimiento;
        IDPreguntasHistoria = idRespestas;
        Notas = notas;
        Peso = peso;
        Talla = talla;
        Edad = CalcularEdad();
        IMC = CalcularIMC();
    }

    public Paciente(string apellidoM, string apellidoP, string direc, string email, string nombre, string telF, string telM, DateOnly nacimiento, int idRespestas, string notas, float peso, float talla)
        : base(apellidoM, apellidoP, direc, email, nombre, telF, telM) 
    {
        FechaNacimiento = nacimiento;
        IDPreguntasHistoria = idRespestas;
        Notas = notas;
        Peso = peso;
        Talla = talla;
        Edad = CalcularEdad();
        IMC = CalcularIMC();
    }

	public int CalcularEdad(){

        DateOnly hoy = DateOnly.FromDateTime(DateTime.Now);
        int edad = hoy.Year - FechaNacimiento.Year;
        return edad;
	}

	public float CalcularIMC(){

		return (float)( Peso / (Talla * Talla));
    }

}//end Paciente