///////////////////////////////////////////////////////////
//  Paciente.cs
//  Implementation of the Class Paciente
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Paciente : Persona {

	private string Alergias;
	private string FechaNacimiento;
	private string IDPreguntasHistoria;
	private string Notas;
	private float Peso;
	private float Talla;
	public ControlPaciente m_ControlPaciente;

	public Paciente(){

	}

	~Paciente(){

	}

	public int CalcularEdad(){

		return 0;
	}

	public float CalcularIMC(){

		return 0;
	}

}//end Paciente