///////////////////////////////////////////////////////////
//  Paciente.cs
//  Implementation of the Class Paciente
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Paciente : Persona {

	public string Alergias { set; get; }
    public string FechaNacimiento { set; get; }
    public string IDPreguntasHistoria { set; get; }
    public string Notas { set; get; }
    public float Peso { set; get; }
    public float Talla { set; get; }

    public ControlPaciente m_ControlPaciente;

	public Paciente(){

	}

	~Paciente(){

	}

	public int CalcularEdad(){

		return 0;
	}

	public float CalcularIMC(){

		return 0;
	}

}//end Paciente