///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Persona {

	private string ApellidoM;
	private string ApellidoP;
	private string Direccion;
	private string DNI;
	private string Email;
	private string idPersona;
	private string Nombre;
	private string TelefonoFijo;
	private string TelefonoMovil;

	public Persona(){

	}

	~Persona(){

	}

}//end Persona