///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Persona {

    public string idPersona { set; get; }
    public string ApellidoM { set; get; }
	public string ApellidoP { set; get; }
    public string Direccion { set; get; }
    public string DNI { set; get; }
    public string Email { set; get; }
    public string Nombre { set; get; }
    public string TelefonoFijo { set; get; }
    public string TelefonoMovil { set; get; }

    public Persona(){

	}

	~Persona(){

	}

}//end Persona