///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Persona {

    public int IdPersona { set; get; }
    public string ApellidoM { set; get; }
	public string ApellidoP { set; get; }
    public string Direccion { set; get; }
    public string Email { set; get; }
    public string Nombre { set; get; }
    public string TelefonoFijo { set; get; }
    public string TelefonoMovil { set; get; }

    public Persona( int idx, string apellidoM, string apellidoP, string direc, string email, string nombre, string telF, string telM ){

        IdPersona = idx;
        ApellidoM = apellidoM;
        ApellidoP = apellidoP;
        Direccion = direc;
        Email = email;
        Nombre = nombre;
        TelefonoFijo = telF;
        TelefonoMovil = telM;
    }

    public Persona( string apellidoM, string apellidoP, string direc, string email, string nombre, string telF, string telM)
    {

        ApellidoM = apellidoM;
        ApellidoP = apellidoP;
        Direccion = direc;
        Email = email;
        Nombre = nombre;
        TelefonoFijo = telF;
        TelefonoMovil = telM;
    }

}//end Persona