///////////////////////////////////////////////////////////
//  PreguntaHistoriaClinica.cs
//  Implementation of the Class PreguntaHistoriaClinica
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PreguntaHistoriaClinica {

    public int IdPregunta { get; set; }
    public string Pregunta { get; set; }

	public PreguntaHistoriaClinica( int idx, string preg){

        IdPregunta = idx;
        Pregunta = preg;
    }

    public PreguntaHistoriaClinica( string preg)
    {
        Pregunta = preg;
    }
}//end PreguntaHistoriaClinica