///////////////////////////////////////////////////////////
//  PreguntaHistoriaClinica.cs
//  Implementation of the Class PreguntaHistoriaClinica
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PreguntaHistoriaClinica {

	private string IDPregunta;
	private string Pregunta;
	private string Respuesta;
	public ControlPreguntas m_ControlPreguntas;

	public PreguntaHistoriaClinica(){

	}

	~PreguntaHistoriaClinica(){

	}

}//end PreguntaHistoriaClinica