///////////////////////////////////////////////////////////
//  Presupuesto.cs
//  Implementation of the Class Presupuesto
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Clases;



public class Presupuesto {

    public int IDPresupuesto { set; get; }
    public DateTime HoraFechaPresupuesto { set; get; }
    public int IDMedico { set; get; }
    public int IDPaciente { set; get; }
    public int IDTratamaiento { set; get; }
    public float MontoTotal { set; get; }
    public string TipoTrabajo { set; get; }
    public string UbicacionBoca { set; get; }

    ControlTratamiento controlTratamiento = new ControlTratamiento();
    public Presupuesto( int idx, DateTime horafesha, int idmedico, int idpaciente, int idtratamiento, string tipo, string ubicacion){
        IDPresupuesto = idx;
        HoraFechaPresupuesto = horafesha;
        IDMedico = idmedico;
        IDPaciente = idpaciente;
        IDTratamaiento = idtratamiento;
        TipoTrabajo = tipo;
        UbicacionBoca = ubicacion;
        MontoTotal = TotalTratamiento();
    }

    public Presupuesto(DateTime horafesha, int idmedico, int idpaciente, int idtratamiento, string tipo, string ubicacion)
    {
        HoraFechaPresupuesto = horafesha;
        IDMedico = idmedico;
        IDPaciente = idpaciente;
        IDTratamaiento = idtratamiento;
        TipoTrabajo = tipo;
        UbicacionBoca = ubicacion;
        MontoTotal = TotalTratamiento();
    }

    public float TotalTratamiento()
    {
        List<Tratamiento> tratamientos = controlTratamiento.ConsultarTratamiento( IDTratamaiento );
        float total = 0;
        foreach (Tratamiento t in tratamientos)
        {
            total += t.SubTotal;
        }
        return total;
    }
}//end Presupuesto