///////////////////////////////////////////////////////////
//  Presupuesto.cs
//  Implementation of the Class Presupuesto
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Presupuesto {

	private string HoraFechaPresupuesto;
	private string IDMedico;
	private string IDPaciente;
	private string IDPresupuesto;
	private string IDTratamaiento;
	private double MontoTotal;
	private string TipoTrabajo;
	private string UbicacionBoca;
	public ControlPresupuesto m_ControlPresupuesto;

	public Presupuesto(){

	}

	~Presupuesto(){

	}

}//end Presupuesto