///////////////////////////////////////////////////////////
//  Presupuesto.cs
//  Implementation of the Class Presupuesto
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Presupuesto {

    public string IDPresupuesto { set; get; }
    public string HoraFechaPresupuesto { set; get; }
    public string IDMedico { set; get; }
    public string IDPaciente { set; get; }
    public string IDTratamaiento { set; get; }
    public double MontoTotal { set; get; }
    public string TipoTrabajo { set; get; }
    public string UbicacionBoca { set; get; }
    public ControlPresupuesto m_ControlPresupuesto;

	public Presupuesto(){

	}

	~Presupuesto(){

	}

}//end Presupuesto