///////////////////////////////////////////////////////////
//  Receta.cs
//  Implementation of the Class Receta
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Receta {

	private string Fecha;
	private string IDMedico;
	private string IDPaciente;
	private string IDReceta;
	private string Indicaciones;
	private List<Medicamento> Medicamentos;
	public ControlReceta m_ControlReceta;

	public Receta(){

	}

	~Receta(){

	}

}//end Receta