///////////////////////////////////////////////////////////
//  Receta.cs
//  Implementation of the Class Receta
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Receta {

    public int IdReceta { get; set; }
    public DateOnly Fecha { set; get; }
    public int IDMedico { set; get; }
    public int IDPaciente { set; get; }
    public string Indicaciones { set; get; }
    public int IdMedicamentosRecetados { get; set; }
    public List<Medicamento> Medicamentos { set; get; }

	public Receta( int idx, DateOnly fesha, int idmed, int idpac, string indic, int idmedicrec ){

        IdReceta = idx;
        Fecha = fesha;
        IDMedico = idmed;
        IDPaciente = idpac;
        Indicaciones = indic;
        IdMedicamentosRecetados = idmedicrec;
        Medicamentos = new List<Medicamento>();
    }

    public Receta( DateOnly fesha, int idmed, int idpac, string indic, int idmedicrec)
    {

        Fecha = fesha;
        IDMedico = idmed;
        IDPaciente = idpac;
        Indicaciones = indic;
        IdMedicamentosRecetados = idmedicrec;
        Medicamentos = new List<Medicamento>();
    }

}//end Receta