///////////////////////////////////////////////////////////
//  Receta.cs
//  Implementation of the Class Receta
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:45 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Receta {

    public string idReceta { get; set; }
    public string Fecha { set; get; }
    public string IDMedico { set; get; }
    public string IDPaciente { set; get; }
    public string Indicaciones { set; get; }
    public List<Medicamento> Medicamentos { set; get; }
    public ControlReceta m_ControlReceta;

	public Receta(){

	}

	~Receta(){

	}

}//end Receta