///////////////////////////////////////////////////////////
//  Reporte.cs
//  Implementation of the Class Reporte
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Reporte {

	private string Fecha;
	private string IDReporte;
	private List<Cita> InformacionCitas;
	private List<ConsultaMedica> InformacionConsultas;
	private List<Medicamento> InformacionMedicamentoVendido;
	private List<Presupuesto> InformacionPresupuestos;
	public ControlReporte m_ControlReporte;

	public Reporte(){

	}

	~Reporte(){

	}

}//end Reporte