///////////////////////////////////////////////////////////
//  Reporte.cs
//  Implementation of the Class Reporte
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:47 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Reporte {

    public int IdReporte { get; set; }
    public DateOnly Fecha { get; set; }

    ControlPresupuesto controlPresupuesto = new ControlPresupuesto();
    ControlReceta controlReceta = new ControlReceta();
    ControlConsulta controlConsulta = new ControlConsulta();
    ControlCajaRegistradora controlCajaRegistradora = new ControlCajaRegistradora();

    public Reporte(int idx, DateOnly fesha ){
        IdReporte = idx;
        Fecha = fesha;
    }

    public Reporte(DateOnly fesha)
    {
        Fecha = fesha;
    }

    public Reporte()
    {
        Fecha = DateOnly.FromDateTime(DateTime.Now);
    }

    public List<Receta> ConsultarRecetas( DateOnly date)
    {
        return controlReceta.ConsultarRecetasPorFecha(date);
    }

    public List<Presupuesto> ConsultarPresupuestos(DateOnly date)
    {
        return controlPresupuesto.ConsultarPresupuestosPorFecha(date);
    }

    public List<ConsultaMedica> ConsultarConsultasMedicas(DateOnly date)
    {
        return controlConsulta.ConsultarConsultasMedicasPorFecha(date);
    }

    public List<CajaRegistradora> ConsultarCajasRegistradoras(DateOnly date)
    {
        return controlCajaRegistradora.ConsultarCajasPorFecha(date);
    }


}//end Reporte