///////////////////////////////////////////////////////////
//  RespuestasClinicas.cs
//  Implementation of the Class RespuestasClinicas
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class RespuestasClinicas {

    public int IdPaciente { get; set; }
    public string Respuesta { get; set; }
    public int IdPregunta { get; set; }

	public RespuestasClinicas( int idx, string resp, int idpregunta ){
        IdPaciente = idx;
        Respuesta = resp;
        IdPregunta = idpregunta;
    }


}//end RespuestasClinicas