///////////////////////////////////////////////////////////
//  RespuestasClinicas.cs
//  Implementation of the Class RespuestasClinicas
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:46 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class RespuestasClinicas {

	private string IDPaciente;
	private string IDRespuestas;
	private List<PreguntaHistoriaClinica> Respuestas;
	public ControlRespuestasClinicas m_ControlRespuestasClinicas;

	public RespuestasClinicas(){

	}

	~RespuestasClinicas(){

	}

}//end RespuestasClinicas