///////////////////////////////////////////////////////////
//  Secretaria.cs
//  Implementation of the Class Secretaria
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Secretaria : Usuario {

	public string Turno { set; get; }

	public Secretaria(int idx, string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass, string turno )
        : base(idx, apellidoM, apellidoP, direc, dni, email, nombre, telF, telM, usuario, pass) 
	{
        Turno = turno;
    }

    public Secretaria(string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass, string turno)
        : base(apellidoM, apellidoP, direc, dni, email, nombre, telF, telM, usuario, pass)
    {
        Turno = turno;
    }


}//end Secretaria