///////////////////////////////////////////////////////////
//  Secretaria.cs
//  Implementation of the Class Secretaria
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:44 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Secretaria : Usuario {

	private string Turno;
	public ControlSecretaria m_ControlSecretaria;

	public Secretaria(){

	}

	~Secretaria(){

	}

	/// 
	/// <param name="IDCita"></param>
	public void CancelarCita(string IDCita){

	}

	public void ConsultarAgenda(){

	}

	/// 
	/// <param name="IDMedico"></param>
	public void ConsultarMedico(string IDMedico){

	}

	public void ConsultarMedicos(){

	}

	/// 
	/// <param name="IDReceta"></param>
	public void ConsultarReceta(string IDReceta){

	}

	public void CrearCita(){

	}

	/// 
	/// <param name="IDPaciente"></param>
	public void EnviarRecordatorio(string IDPaciente){

	}

	/// 
	/// <param name="IDPaciente"></param>
	public void ModificarPaciente(string IDPaciente){

	}

}//end Secretaria