///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Transactions;


public class Usuario : Persona {

    public string DNI { get; set; }
    public string NombreUsuario { set; get; }
    public string Password { set; get; }


	public Usuario(int idx, string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass )
		: base (idx, apellidoM, apellidoP, direc, email, nombre, telF, telM) {

        NombreUsuario = usuario;
        Password = pass;
        DNI = dni;
    }

    public Usuario( string apellidoM, string apellidoP, string direc, string dni, string email, string nombre, string telF, string telM, string usuario, string pass)
        : base( apellidoM, apellidoP, direc, email, nombre, telF, telM)
    {

        NombreUsuario = usuario;
        Password = pass;
        DNI = dni;
    }

}//end Usuario