///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:43 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Usuario : Persona {

	private string NombreUsuario;
	private string Password;
	public ValidarUsuario m_ValidarUsuario;

	public Usuario(){

	}

	~Usuario(){

	}

}//end Usuario