///////////////////////////////////////////////////////////
//  ValidarUsuario.cs
//  Implementation of the Class ValidarUsuario
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:48 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using MySql.Data.MySqlClient;
using System.Data;



public class ValidarUsuario {

	public MySqlCommand cmd = new MySqlCommand();
    public MySqlConnection conn = new MySqlConnection();
	public MySqlDataReader dr;

    string server = "192.168.1.74";
	string user = "nuevoUsuario";
    string pwd = "1234";
    string database = "dbClinica_Dental";

	public int indice = -1;
    public string tipo = "null";
    public string mensaje = "";

	public void conectar()
	{
		conn.ConnectionString = $"Server={server};Database={database}; Uid={user};Pwd={pwd}";
		conn.Open();
    }

    public void desconectar()
	{
		conn.Close();
    }

    public bool validar(string nUsuario, string pass)
    {
        bool bandera = false;

        // admin_, secre_, denta_ : sufijos para los nombres de usuario

        string nueva = "";

        if ( nUsuario.Length > 0)
        {
            nueva = nUsuario.Substring(0, 4);
        }
        

        switch (nueva)
        {
            case "adm_":
                try
                {
                    conectar();
                    cmd = new MySqlCommand("uspValidarAdministrador", conn);
                    cmd.CommandType = CommandType.StoredProcedure;

                    MySqlParameter a_usuario = new MySqlParameter("p_usuario", MySqlDbType.VarChar, 15);
                    a_usuario.Value = nUsuario;
                    cmd.Parameters.Add(a_usuario);

                    MySqlParameter a_pass = new MySqlParameter("p_password", MySqlDbType.VarChar, 20);
                    a_pass.Value = pass;
                    cmd.Parameters.Add(a_pass);

                    dr = cmd.ExecuteReader();

                    if (dr.Read())
                    {
                        indice = Convert.ToInt32(dr["idx"]);
                        tipo = "admin";
                        bandera = true;
                    }
                }
                catch (MySqlException ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                    }
                    desconectar();
                }
                break;

            case "sec_":

                try
                {
                    conectar();
                    cmd = new MySqlCommand("uspValidarSecretaria", conn);
                    cmd.CommandType = CommandType.StoredProcedure;

                    MySqlParameter a_usuario = new MySqlParameter("p_usuario", MySqlDbType.VarChar, 15);
                    a_usuario.Value = nUsuario;
                    cmd.Parameters.Add(a_usuario);

                    MySqlParameter a_pass = new MySqlParameter("p_password", MySqlDbType.VarChar, 20);
                    a_pass.Value = pass;
                    cmd.Parameters.Add(a_pass);

                    dr = cmd.ExecuteReader();
                    if (dr.Read())
                    {
                        indice = Convert.ToInt32(dr["idx"]);
                        tipo = "secre";
                        bandera = true;
                    }
                }
                catch (MySqlException ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                    }
                    desconectar();

                }
                break;

            case "den_":

                try
                {
                    conectar();
                    cmd = new MySqlCommand("uspValidarMedico", conn);
                    cmd.CommandType = CommandType.StoredProcedure;

                    MySqlParameter a_usuario = new MySqlParameter("p_usuario", MySqlDbType.VarChar, 15);
                    a_usuario.Value = nUsuario;
                    cmd.Parameters.Add(a_usuario);

                    MySqlParameter a_pass = new MySqlParameter("p_password", MySqlDbType.VarChar, 20);
                    a_pass.Value = pass;
                    cmd.Parameters.Add(a_pass);

                    dr = cmd.ExecuteReader();
                    if (dr.Read())
                    {
                        indice = Convert.ToInt32(dr["idx"]);
                        tipo = "dent";
                        bandera = true;
                    }
                }
                catch (MySqlException ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                    }
                    desconectar();
                }
                break;

            default:
                mensaje = "El nombre de usuario no es correcto";
                break;
        }
        return bandera;
    }
}//end ValidarUsuario