///////////////////////////////////////////////////////////
//  ValidarUsuario.cs
//  Implementation of the Class ValidarUsuario
//  Generated by Enterprise Architect
//  Created on:      06-abr.-2025 10:21:48 p. m.
//  Original author: carre
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ValidarUsuario {

	private Usuario Usuario;
	public frmLogin m_frmLogin;

	public ValidarUsuario(){

	}

	~ValidarUsuario(){

	}

	public void CargarFormulario(){

	}

	/// 
	/// <param name="NombreUsuario"></param>
	/// <param name="password"></param>
	public Usuario ConsultarUsuario(string NombreUsuario, string password){

		return null;
	}

	public bool GetAutorización(){

		return false;
	}

}//end ValidarUsuario